// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQIJY8E8IIJrPNEJhdn1g7FWUwFvkoMk',
    appId: '1:1001420856250:web:03bad8b0cdfaf5cb191b83',
    messagingSenderId: '1001420856250',
    projectId: 'shia-comapnion',
    authDomain: 'shia-comapnion.firebaseapp.com',
    databaseURL: 'https://shia-comapnion.firebaseio.com',
    storageBucket: 'shia-comapnion.firebasestorage.app',
    measurementId: 'G-EBF2XT6WXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo0sNZjdU-MQTvsTj5IKcN4L3M9znH-i8',
    appId: '1:1001420856250:android:0876f1e991794213',
    messagingSenderId: '1001420856250',
    projectId: 'shia-comapnion',
    databaseURL: 'https://shia-comapnion.firebaseio.com',
    storageBucket: 'shia-comapnion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmw1PpJZ-NJbCavQxe0PS8Ij6pXzfcKg',
    appId: '1:1001420856250:ios:ced79f30fcbcf422191b83',
    messagingSenderId: '1001420856250',
    projectId: 'shia-comapnion',
    databaseURL: 'https://shia-comapnion.firebaseio.com',
    storageBucket: 'shia-comapnion.firebasestorage.app',
    androidClientId:
        '1001420856250-26dbel6vu7gachlntmo6decth4epcg6l.apps.googleusercontent.com',
    iosClientId:
        '1001420856250-clrf0hrb1jgpuv0avehouki158r6lccc.apps.googleusercontent.com',
    iosBundleId: 'com.developer110.shiacompanion',
  );
}
